#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo ':::::::: Run husky post-merge ::::::::'
echo ':::::::: Run husky post-merge ::::::::'

if ! git diff HEAD^ HEAD --exit-code -- ./package.json; then
    npm ci
fi