#
name: cron-v2

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  cron:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    # 현재 레파지토리를 체크아웃합니다.
    # https://github.com/actions/checkout
    steps:
      - uses: actions/checkout@v2

      # Nodejs를 셋업합니다.
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.0
        with:
          node-version: ${{ matrix.node-version }}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

      # Package.json Cache
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      # Run CI
      - name: CI
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Run a multi-line script
        run: |
          echo Cron !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!,
          echo Cron !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!.
