name: push-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.0
        with:
          node-version: ${{ matrix.node-version }}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: CI
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Run a one-line script
        run: echo Hello, world!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!,
          echo test, and deploy your project!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!.
