#
name: push-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js node-version: ${{ secrets.NODE_VERSION }}
        uses: actions/setup-node@v2.1.0
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: CI
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Run a multi-line script
        run: |
          echo Cron !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!,
          echo Cron !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!.
